import { z } from "zod";

const availableLanguages = [
  "English",
  "Spanish",
  "Mandarin Chinese",
  "Hindi",
  "Arabic",
  "Portuguese",
  "Bengali",
  "Russian",
  "Japanese",
  "Punjabi",
  "German",
  "Javanese",
  "Wu Chinese",
  "Korean",
  "French",
  "Telugu",
  "Vietnamese",
  "Marathi",
  "Tamil",
  "Urdu",
  "Turkish",
  "Italian",
  "Yue Chinese",
  "Thai",
  "Gujarati",
  "Jin Chinese",
  "Persian",
  "Polish",
  "Pashto",
  "Kannada",
  "Xiang Chinese",
  "Malayalam",
  "Sundanese",
  "Hausa",
  "Odia",
  "Burmese",
  "Hakka Chinese",
  "Ukrainian",
  "Bhojpuri",
  "Tagalog",
  "Yoruba",
  "Maithili",
  "Uzbek",
  "Sindhi",
  "Amharic",
  "Fula",
  "Romanian",
  "Igbo",
  "Oromo",
  "Azerbaijani",
  "Awadhi",
  "Gan Chinese",
  "Cebuano",
  "Dutch",
  "Kurdish",
  "Serbo-Croatian",
  "Malagasy",
  "Saraiki",
  "Nepali",
  "Sinhalese",
  "Chittagonian",
  "Zhuang Chinese",
  "Khmer",
  "Turkmen",
  "Assamese",
  "Madurese",
  "Somali",
  "Marwari",
  "Magahi",
  "Haryanvi",
  "Hungarian",
  "Chhattisgarhi",
  "German Swahili",
  "Zulu",
  "Ilocano",
  "Hejazi Arabic",
  "Kaonde",
  "Kinyarwanda",
  "Dhundari",
  "Haitian Creole",
  "Hausa",
  "Bihari",
  "Yiddish",
  "Modern Greek",
  "Xhosa",
  "Oromiffa",
  "Mossi",
  "Belarusian",
  "Albanian",
  "Saraiki",
  "Nigerian Fulfulde",
  "Mandinka",
  "Nyanja",
  "Zande",
] as const;

export const createLanguageSchema = z.object({
  userId: z.string(),
  name: z.enum(availableLanguages),
  purpose: z.string().optional(),
});
